package korat.instrumentation.bytecode;

/**
 * 
 * @author Aleksandar Milicevic <aca.milicevic@gmail.com>
 *
 */
public class VisitorSupport implements BytecodeVisitor {

    public void postVisit(BytecodeInstruction instr) {}
    public void preVisit(BytecodeInstruction instr) {}
    
    public void visitNOP (BytecodeInstruction instr) {}
    public void visitACONST_NULL (BytecodeInstruction instr) {}
    public void visitICONST_M1 (BytecodeInstruction instr) {}
    public void visitICONST_0 (BytecodeInstruction instr) {}
    public void visitICONST_1 (BytecodeInstruction instr) {}
    public void visitICONST_2 (BytecodeInstruction instr) {}
    public void visitICONST_3 (BytecodeInstruction instr) {}
    public void visitICONST_4 (BytecodeInstruction instr) {}
    public void visitICONST_5 (BytecodeInstruction instr) {}
    public void visitLCONST_0 (BytecodeInstruction instr) {}
    public void visitLCONST_1 (BytecodeInstruction instr) {}
    public void visitFCONST_0 (BytecodeInstruction instr) {}
    public void visitFCONST_1 (BytecodeInstruction instr) {}
    public void visitFCONST_2 (BytecodeInstruction instr) {}
    public void visitDCONST_0 (BytecodeInstruction instr) {}
    public void visitDCONST_1 (BytecodeInstruction instr) {}
    public void visitBIPUSH (BytecodeInstruction instr) {}
    public void visitSIPUSH (BytecodeInstruction instr) {}
    public void visitLDC (BytecodeInstruction instr) {}
    public void visitLDC_W (BytecodeInstruction instr) {}
    public void visitLDC2_W (BytecodeInstruction instr) {}
    public void visitILOAD (BytecodeInstruction instr) {}
    public void visitLLOAD (BytecodeInstruction instr) {}
    public void visitFLOAD (BytecodeInstruction instr) {}
    public void visitDLOAD (BytecodeInstruction instr) {}
    public void visitALOAD (BytecodeInstruction instr) {}
    public void visitILOAD_0 (BytecodeInstruction instr) {}
    public void visitILOAD_1 (BytecodeInstruction instr) {}
    public void visitILOAD_2 (BytecodeInstruction instr) {}
    public void visitILOAD_3 (BytecodeInstruction instr) {}
    public void visitLLOAD_0 (BytecodeInstruction instr) {}
    public void visitLLOAD_1 (BytecodeInstruction instr) {}
    public void visitLLOAD_2 (BytecodeInstruction instr) {}
    public void visitLLOAD_3 (BytecodeInstruction instr) {}
    public void visitFLOAD_0 (BytecodeInstruction instr) {}
    public void visitFLOAD_1 (BytecodeInstruction instr) {}
    public void visitFLOAD_2 (BytecodeInstruction instr) {}
    public void visitFLOAD_3 (BytecodeInstruction instr) {}
    public void visitDLOAD_0 (BytecodeInstruction instr) {}
    public void visitDLOAD_1 (BytecodeInstruction instr) {}
    public void visitDLOAD_2 (BytecodeInstruction instr) {}
    public void visitDLOAD_3 (BytecodeInstruction instr) {}
    public void visitALOAD_0 (BytecodeInstruction instr) {}
    public void visitALOAD_1 (BytecodeInstruction instr) {}
    public void visitALOAD_2 (BytecodeInstruction instr) {}
    public void visitALOAD_3 (BytecodeInstruction instr) {}
    public void visitIALOAD (BytecodeInstruction instr) {}
    public void visitLALOAD (BytecodeInstruction instr) {}
    public void visitFALOAD (BytecodeInstruction instr) {}
    public void visitDALOAD (BytecodeInstruction instr) {}
    public void visitAALOAD (BytecodeInstruction instr) {}
    public void visitBALOAD (BytecodeInstruction instr) {}
    public void visitCALOAD (BytecodeInstruction instr) {}
    public void visitSALOAD (BytecodeInstruction instr) {}
    public void visitISTORE (BytecodeInstruction instr) {}
    public void visitLSTORE (BytecodeInstruction instr) {}
    public void visitFSTORE (BytecodeInstruction instr) {}
    public void visitDSTORE (BytecodeInstruction instr) {}
    public void visitASTORE (BytecodeInstruction instr) {}
    public void visitISTORE_0 (BytecodeInstruction instr) {}
    public void visitISTORE_1 (BytecodeInstruction instr) {}
    public void visitISTORE_2 (BytecodeInstruction instr) {}
    public void visitISTORE_3 (BytecodeInstruction instr) {}
    public void visitLSTORE_0 (BytecodeInstruction instr) {}
    public void visitLSTORE_1 (BytecodeInstruction instr) {}
    public void visitLSTORE_2 (BytecodeInstruction instr) {}
    public void visitLSTORE_3 (BytecodeInstruction instr) {}
    public void visitFSTORE_0 (BytecodeInstruction instr) {}
    public void visitFSTORE_1 (BytecodeInstruction instr) {}
    public void visitFSTORE_2 (BytecodeInstruction instr) {}
    public void visitFSTORE_3 (BytecodeInstruction instr) {}
    public void visitDSTORE_0 (BytecodeInstruction instr) {}
    public void visitDSTORE_1 (BytecodeInstruction instr) {}
    public void visitDSTORE_2 (BytecodeInstruction instr) {}
    public void visitDSTORE_3 (BytecodeInstruction instr) {}
    public void visitASTORE_0 (BytecodeInstruction instr) {}
    public void visitASTORE_1 (BytecodeInstruction instr) {}
    public void visitASTORE_2 (BytecodeInstruction instr) {}
    public void visitASTORE_3 (BytecodeInstruction instr) {}
    public void visitIASTORE (BytecodeInstruction instr) {}
    public void visitLASTORE (BytecodeInstruction instr) {}
    public void visitFASTORE (BytecodeInstruction instr) {}
    public void visitDASTORE (BytecodeInstruction instr) {}
    public void visitAASTORE (BytecodeInstruction instr) {}
    public void visitBASTORE (BytecodeInstruction instr) {}
    public void visitCASTORE (BytecodeInstruction instr) {}
    public void visitSASTORE (BytecodeInstruction instr) {}
    public void visitPOP (BytecodeInstruction instr) {}
    public void visitPOP2 (BytecodeInstruction instr) {}
    public void visitDUP (BytecodeInstruction instr) {}
    public void visitDUP_X1 (BytecodeInstruction instr) {}
    public void visitDUP_X2 (BytecodeInstruction instr) {}
    public void visitDUP2 (BytecodeInstruction instr) {}
    public void visitDUP2_X1 (BytecodeInstruction instr) {}
    public void visitDUP2_X2 (BytecodeInstruction instr) {}
    public void visitSWAP (BytecodeInstruction instr) {}
    public void visitIADD (BytecodeInstruction instr) {}
    public void visitLADD (BytecodeInstruction instr) {}
    public void visitFADD (BytecodeInstruction instr) {}
    public void visitDADD (BytecodeInstruction instr) {}
    public void visitISUB (BytecodeInstruction instr) {}
    public void visitLSUB (BytecodeInstruction instr) {}
    public void visitFSUB (BytecodeInstruction instr) {}
    public void visitDSUB (BytecodeInstruction instr) {}
    public void visitIMUL (BytecodeInstruction instr) {}
    public void visitLMUL (BytecodeInstruction instr) {}
    public void visitFMUL (BytecodeInstruction instr) {}
    public void visitDMUL (BytecodeInstruction instr) {}
    public void visitIDIV (BytecodeInstruction instr) {}
    public void visitLDIV (BytecodeInstruction instr) {}
    public void visitFDIV (BytecodeInstruction instr) {}
    public void visitDDIV (BytecodeInstruction instr) {}
    public void visitIREM (BytecodeInstruction instr) {}
    public void visitLREM (BytecodeInstruction instr) {}
    public void visitFREM (BytecodeInstruction instr) {}
    public void visitDREM (BytecodeInstruction instr) {}
    public void visitINEG (BytecodeInstruction instr) {}
    public void visitLNEG (BytecodeInstruction instr) {}
    public void visitFNEG (BytecodeInstruction instr) {}
    public void visitDNEG (BytecodeInstruction instr) {}
    public void visitISHL (BytecodeInstruction instr) {}
    public void visitLSHL (BytecodeInstruction instr) {}
    public void visitISHR (BytecodeInstruction instr) {}
    public void visitLSHR (BytecodeInstruction instr) {}
    public void visitIUSHR (BytecodeInstruction instr) {}
    public void visitLUSHR (BytecodeInstruction instr) {}
    public void visitIAND (BytecodeInstruction instr) {}
    public void visitLAND (BytecodeInstruction instr) {}
    public void visitIOR (BytecodeInstruction instr) {}
    public void visitLOR (BytecodeInstruction instr) {}
    public void visitIXOR (BytecodeInstruction instr) {}
    public void visitLXOR (BytecodeInstruction instr) {}
    public void visitIINC (BytecodeInstruction instr) {}
    public void visitI2L (BytecodeInstruction instr) {}
    public void visitI2F (BytecodeInstruction instr) {}
    public void visitI2D (BytecodeInstruction instr) {}
    public void visitL2I (BytecodeInstruction instr) {}
    public void visitL2F (BytecodeInstruction instr) {}
    public void visitL2D (BytecodeInstruction instr) {}
    public void visitF2I (BytecodeInstruction instr) {}
    public void visitF2L (BytecodeInstruction instr) {}
    public void visitF2D (BytecodeInstruction instr) {}
    public void visitD2I (BytecodeInstruction instr) {}
    public void visitD2L (BytecodeInstruction instr) {}
    public void visitD2F (BytecodeInstruction instr) {}
    public void visitI2B (BytecodeInstruction instr) {}
    public void visitI2C (BytecodeInstruction instr) {}
    public void visitI2S (BytecodeInstruction instr) {}
    public void visitLCMP (BytecodeInstruction instr) {}
    public void visitFCMPL (BytecodeInstruction instr) {}
    public void visitFCMPG (BytecodeInstruction instr) {}
    public void visitDCMPL (BytecodeInstruction instr) {}
    public void visitDCMPG (BytecodeInstruction instr) {}
    public void visitIFEQ (BytecodeInstruction instr) {}
    public void visitIFNE (BytecodeInstruction instr) {}
    public void visitIFLT (BytecodeInstruction instr) {}
    public void visitIFGE (BytecodeInstruction instr) {}
    public void visitIFGT (BytecodeInstruction instr) {}
    public void visitIFLE (BytecodeInstruction instr) {}
    public void visitIF_ICMPEQ (BytecodeInstruction instr) {}
    public void visitIF_ICMPNE (BytecodeInstruction instr) {}
    public void visitIF_ICMPLT (BytecodeInstruction instr) {}
    public void visitIF_ICMPGE (BytecodeInstruction instr) {}
    public void visitIF_ICMPGT (BytecodeInstruction instr) {}
    public void visitIF_ICMPLE (BytecodeInstruction instr) {}
    public void visitIF_ACMPEQ (BytecodeInstruction instr) {}
    public void visitIF_ACMPNE (BytecodeInstruction instr) {}
    public void visitGOTO (BytecodeInstruction instr) {}
    public void visitJSR (BytecodeInstruction instr) {}
    public void visitRET (BytecodeInstruction instr) {}
    public void visitTABLESWITCH (BytecodeInstruction instr) {}
    public void visitLOOKUPSWITCH (BytecodeInstruction instr) {}
    public void visitIRETURN (BytecodeInstruction instr) {}
    public void visitLRETURN (BytecodeInstruction instr) {}
    public void visitFRETURN (BytecodeInstruction instr) {}
    public void visitDRETURN (BytecodeInstruction instr) {}
    public void visitARETURN (BytecodeInstruction instr) {}
    public void visitRETURN (BytecodeInstruction instr) {}
    public void visitGETSTATIC (BytecodeInstruction instr) {}
    public void visitPUTSTATIC (BytecodeInstruction instr) {}
    public void visitGETFIELD (BytecodeInstruction instr) {}
    public void visitPUTFIELD (BytecodeInstruction instr) {}
    public void visitINVOKEVIRTUAL (BytecodeInstruction instr) {}
    public void visitINVOKESPECIAL (BytecodeInstruction instr) {}
    public void visitINVOKESTATIC (BytecodeInstruction instr) {}
    public void visitINVOKEINTERFACE (BytecodeInstruction instr) {}
    public void visitNEW (BytecodeInstruction instr) {}
    public void visitNEWARRAY (BytecodeInstruction instr) {}
    public void visitANEWARRAY (BytecodeInstruction instr) {}
    public void visitARRAYLENGTH (BytecodeInstruction instr) {}
    public void visitATHROW (BytecodeInstruction instr) {}
    public void visitCHECKCAST (BytecodeInstruction instr) {}
    public void visitINSTANCEOF (BytecodeInstruction instr) {}
    public void visitMONITORENTER (BytecodeInstruction instr) {}
    public void visitMONITOREXIT (BytecodeInstruction instr) {}
    public void visitWIDE (BytecodeInstruction instr) {}
    public void visitMULTIANEWARRAY (BytecodeInstruction instr) {}
    public void visitIFNULL (BytecodeInstruction instr) {}
    public void visitIFNONNULL (BytecodeInstruction instr) {}
    public void visitGOTO_W (BytecodeInstruction instr) {}
    public void visitJSR_W (BytecodeInstruction instr) {}
    public void visitBREAKPOINT (BytecodeInstruction instr) {}
    public void visitIMPDEP1 (BytecodeInstruction instr) {}
    public void visitIMPDEP2 (BytecodeInstruction instr) {}

}
